#include "Synth/SynthCaptureDirector.h"

#include "SynthicCamera.h"
#include "Synth/SynthVehicle.h"
#include "Engine/World.h"
#include "Misc/CommandLine.h"
#include "Misc/Parse.h"

ASynthCaptureDirector::ASynthCaptureDirector()
{
	PrimaryActorTick.bCanEverTick = true;
	SetRootComponent(CreateDefaultSubobject<USceneComponent>(TEXT("DirectorRoot")));
}

TArray<FSynthVehicleSpec> ASynthCaptureDirector::MakeDefaultCatalog()
{
	// Proxy stand-ins with real-world dimensions. Make is deliberately "PROXY" so no
	// one mistakes a box for a real vehicle signature in the output. Point Spec.Mesh at
	// an imported asset to promote an entry to the real thing - no code change needed.
	auto Entry = [](const TCHAR* Model, ESynthVehicleClass Class, FVector Dims, int32 Axles, bool bTracked,
		const TCHAR* Livery, FLinearColor Colour)
	{
		FSynthVehicleSpec Spec;
		Spec.Make = TEXT("PROXY");
		Spec.Model = Model;
		Spec.VehicleClass = Class;
		Spec.DimensionsCm = Dims;
		Spec.AxleCount = Axles;
		Spec.bTracked = bTracked;
		Spec.LiveryName = Livery;
		Spec.LiveryColor = Colour;
		return Spec;
	};

	// Distinct liveries so the colour field in the label is actually present in the
	// pixels. Identical colours would make it a field a model can only learn to ignore.
	return {
		Entry(TEXT("LightUtility4x4"), ESynthVehicleClass::LightUtility, FVector(480, 210, 195), 2, false,
			TEXT("desert-tan"), FLinearColor(0.42f, 0.34f, 0.20f)),
		Entry(TEXT("CargoTruck6x6"), ESynthVehicleClass::CargoTruck, FVector(780, 250, 290), 3, false,
			TEXT("olive-drab"), FLinearColor(0.16f, 0.18f, 0.11f)),
		Entry(TEXT("WheeledAPC8x8"), ESynthVehicleClass::APC, FVector(780, 290, 270), 4, false,
			TEXT("nato-green"), FLinearColor(0.13f, 0.20f, 0.14f)),
		Entry(TEXT("TrackedIFV"), ESynthVehicleClass::IFV, FVector(660, 320, 260), 0, true,
			TEXT("sand-grey"), FLinearColor(0.38f, 0.35f, 0.28f)),
		Entry(TEXT("MainBattleTank"), ESynthVehicleClass::MBT, FVector(990, 370, 245), 0, true,
			TEXT("olive-drab"), FLinearColor(0.16f, 0.18f, 0.11f))
	};
}

void ASynthCaptureDirector::BeginPlay()
{
	Super::BeginPlay();

	if (Catalog.IsEmpty())
	{
		Catalog = MakeDefaultCatalog();
		UE_LOG(LogSynthic, Warning, TEXT("Director: no catalog authored, using %d proxy archetypes."), Catalog.Num());
	}

	if (MaxSpeedKph < MinSpeedKph)
	{
		UE_LOG(LogSynthic, Error, TEXT("Director: MaxSpeedKph (%.1f) is below MinSpeedKph (%.1f); no traffic will run."),
			MaxSpeedKph, MinSpeedKph);
		return;
	}

	Stream.Initialize(RandomSeed);
	UE_LOG(LogSynthic, Log, TEXT("Director: %d passes, seed %d, speeds %.0f-%.0f km/h."),
		NumPasses, RandomSeed, MinSpeedKph, MaxSpeedKph);

	DispatchNextVehicle();
}

void ASynthCaptureDirector::Tick(float DeltaSeconds)
{
	Super::Tick(DeltaSeconds);

	if (!ActiveVehicle)
	{
		return;		// run finished, or never started
	}

	if (ActiveVehicle->GetDistanceTravelledCm() < TravelDistanceCm)
	{
		return;		// still on the road
	}

	ActiveVehicle->Destroy();
	ActiveVehicle = nullptr;
	DispatchNextVehicle();
}

bool ASynthCaptureDirector::DispatchNextVehicle()
{
	if (PassesDispatched >= NumPasses)
	{
		UE_LOG(LogSynthic, Log, TEXT("Director: run complete, %d passes dispatched."), PassesDispatched);

		// Lets a whole dataset be generated by one headless command that actually ends.
		if (FParse::Param(FCommandLine::Get(), TEXT("SynthAutoQuit")))
		{
			UE_LOG(LogSynthic, Log, TEXT("Director: -SynthAutoQuit set, exiting."));
			FPlatformMisc::RequestExit(false);
		}
		return false;
	}

	const FSynthVehicleSpec& Spec = Catalog[Stream.RandRange(0, Catalog.Num() - 1)];
	const float SpeedKph = Stream.FRandRange(MinSpeedKph, MaxSpeedKph);
	const float LaneOffset = Stream.FRandRange(-LaneJitterCm, LaneJitterCm);

	const FVector SpawnLocation = GetActorLocation() + (GetActorRightVector() * LaneOffset);

	FActorSpawnParameters SpawnParameters;
	SpawnParameters.SpawnCollisionHandlingOverride = ESpawnActorCollisionHandlingMethod::AlwaysSpawn;

	ActiveVehicle = GetWorld()->SpawnActor<ASynthVehicle>(
		ASynthVehicle::StaticClass(), SpawnLocation, GetActorRotation(), SpawnParameters);

	if (!ActiveVehicle)
	{
		UE_LOG(LogSynthic, Error, TEXT("Director: SpawnActor failed on pass %d; aborting run."), PassesDispatched);
		return false;
	}

	ActiveVehicle->ApplySpec(Spec);
	ActiveVehicle->DriveAlong(GetActorForwardVector(), SpeedKph);
	++PassesDispatched;

	UE_LOG(LogSynthic, Log, TEXT("Director: pass %d/%d - %s at %.1f km/h from %s, recycling after %.0fcm."),
		PassesDispatched, NumPasses, *Spec.Model, SpeedKph,
		*ActiveVehicle->GetActorLocation().ToCompactString(), TravelDistanceCm);

	return true;
}
